#!/bin/bash

# https://stackoverflow.com/a/8296746/6244924
function _xargs() {
  if [[ $OSTYPE == 'darwin'* ]]; then
    xargs $@
  else 
    xargs --no-run-if-empty $@
  fi
}

full_diff=$(git diff --name-only HEAD @{push} || git diff --name-only HEAD dev)

merge_diff=$(git log --merges --first-parent --format='%H' | _xargs git show --first-parent --name-only --format='')

if [ -z "$merge_diff" ]; then
  printf '%s\n' "$full_diff"
else
  difference=$(comm --nocheck-order -23 <(printf "%s\n" "${full_diff[@]}" | sort) <(printf "%s\n" "${merge_diff[@]}" | sort))
  printf '%s\n' "$difference" | awk '{$1=$1};1'
fi
