#!/bin/bash

set -e
# set -x

n() {
  $@ &>/dev/null
}

make_file() {
  local branch=$(git branch --show-current)
  touch x/$branch-$1
  git add x
  n git commit -m $1
}

checkout() {
  n git checkout $1
}

push() {
  n git push -f -u testing HEAD
}

merge() {
  n git merge $1 -m $2-merge
}

reset_tests() {
  checkout master
  n git branch -D dev feature old || true
  n git push testing --delete dev feature old || true

  n git checkout -b dev

  make_file a
  push
}

make_old() {
  make_file b
  n git checkout HEAD~1
  n git branch old
  checkout old
  make_file z
  checkout dev
  merge old c
  push
}

make_feature() {
  n git branch feature
  checkout feature
  push
  # git branch -u testing/feature
}

run_test() {
  local result=$(./get-files-push)
  if [ -z "$result" ]; then
    echo -
  else
    echo -e "$result"
  fi
}



#
# --A--  commit
# -{A}-  merge commit
# -(A)-  commit on remote
#


echo
echo



# =================================
#
#     (dev)     --(A)-(B)-(C)-(D)
#                   \     / \   \
#     (feature)      \   /   E--{G}
#                     \ /
#     (old)            Z
#
echo 
echo TEST 14 - feature branch is created from dev with merges and synced with dev
echo x/feature-e
echo 

reset_tests
make_old
make_file c
make_file d
push
n git checkout HEAD~1
make_feature
make_file e
merge dev g

echo RESULT 14
run_test
echo







echo
echo


# n git checkout master
